//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedKernel.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SharedKernel.Resources.ResourceErrorMessages", typeof(ResourceErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string PROJECT_NOT_FOUND {
            get {
                return ResourceManager.GetString("PROJECT_NOT_FOUND", resourceCulture);
            }
        }
        
        public static string NAME_REQUIRED {
            get {
                return ResourceManager.GetString("NAME_REQUIRED", resourceCulture);
            }
        }
        
        public static string NAME_MAX_LENGTH {
            get {
                return ResourceManager.GetString("NAME_MAX_LENGTH", resourceCulture);
            }
        }
        
        public static string DESCRIPTION_MAX_LENGTH {
            get {
                return ResourceManager.GetString("DESCRIPTION_MAX_LENGTH", resourceCulture);
            }
        }
        
        public static string TITLE_REQUIRED {
            get {
                return ResourceManager.GetString("TITLE_REQUIRED", resourceCulture);
            }
        }
        
        public static string TITLE_MAX_LENGTH {
            get {
                return ResourceManager.GetString("TITLE_MAX_LENGTH", resourceCulture);
            }
        }
        
        public static string RESPONSIBLE_NOT_FOUND {
            get {
                return ResourceManager.GetString("RESPONSIBLE_NOT_FOUND", resourceCulture);
            }
        }

        public static string TASK_NOT_FOUND {
            get {
                return ResourceManager.GetString("TASK_NOT_FOUND", resourceCulture);
            }
        }
        
        public static string PRIORITY_INVALID {
            get {
                return ResourceManager.GetString("PRIORITY_INVALID", resourceCulture);
            }
        }
        
        public static string STATUS_INVALID {
            get {
                return ResourceManager.GetString("STATUS_INVALID", resourceCulture);
            }
        }
        
        public static string DEADLINE_PAST {
            get {
                return ResourceManager.GetString("DEADLINE_PAST", resourceCulture);
            }
        }
        
        public static string STATUS_TRANSITION_INVALID
        {
            get
            {
                return ResourceManager.GetString("STATUS_TRANSITION_INVALID", resourceCulture);
            }
        }
        
        public static string TASK_IN_PROGRESS_CANNOT_BE_DELETED {
            get {
                return ResourceManager.GetString("TASK_IN_PROGRESS_CANNOT_BE_DELETED", resourceCulture);
            }
        }
        
        public static string PROJECT_HAS_TASKS {
            get {
                return ResourceManager.GetString("PROJECT_HAS_TASKS", resourceCulture);
            }
        }
    }
}
